<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE REIT [
  <!ELEMENT REIT (SPECIALIZATION)*>
  <!ELEMENT SPECOALIZATION (UNIVER,BALL,MEST,GOROD)>
  <!ELEMENT UNIVER (#PCDATA)>
  <!ELEMENT BALL (#PCDATA)>
  <!ELEMENT MEST (#PCDATA)>
  <!ELEMENT GOROD (#PCDATA)>
]>
<REIT>
  <SPECIALIZATION>
    <UNIVER>BrSTU</UNIVER>
    <BALL>324</BALL>
    <MEST>30</MEST>
    <GOROD>BREST</GOROD>
  </SPECIALIZATION>
  <SPECIALIZATION>
    <UNIVER>BSTU</UNIVER>
    <BALL>298</BALL>
    <MEST>50</MEST>
    <GOROD>MINSK</GOROD>
  </SPECIALIZATION>
  <SPECIALIZATION>
    <UNIVER>BGUiR</UNIVER>
    <BALL>350</BALL>
    <MEST>53</MEST>
    <GOROD>MINSK</GOROD>
  </SPECIALIZATION>
  <SPECIALIZATION>
    <UNIVER>BGU</UNIVER>
    <BALL>360</BALL>
    <MEST>15</MEST>
    <GOROD>MINSK</GOROD>
  </SPECIALIZATION>
</REIT>
